apiVersion: "nais.io/v1alpha1"
kind: Application
metadata:
  name: {{ name }}
  namespace: bidrag
  labels:
    team: bidrag
spec:
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: {{ name }}
    outbound:
      external:
        - host: {{ azure.familiebasak_url }}
        - host: {{ azure.bidraggcpproxy_url }}
  image: {{ image }}
  liveness:
    path: /bidrag-grunnlag/actuator/health
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /bidrag-grunnlag/actuator/health
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /bidrag-grunnlag/actuator/prometheus
  resources:
    limits:
      cpu: 1000m
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 1024Mi
  ingresses:
    - {{ ingress }}
  env:
    - name: FAMILIEBASAK_URL
      value: https://{{ azure.familiebasak_url }}
    - name: FAMILIEBASAK_SCOPE
      value: {{ azure.familiebasak_scope }}
    - name: BIDRAGGCPPROXY_URL
      value: https://{{ azure.bidraggcpproxy_url }}
    - name: BIDRAGGCPPROXY_SCOPE
      value: {{ azure.bidraggcpproxy_scope }}
  gcp:
    sqlInstances:
      - name: {{ dbname }}
        type: POSTGRES_12
        cascadingDelete: true
        databases:
          - name: {{ dbname }}
            envVarPrefix: DB
