apiVersion: "nais.io/v1alpha1"
kind: Application
metadata:
  name: {{ name }}
  namespace: bidrag
  labels:
    team: bidrag
spec:
  azure:
    application:
      enabled: true
      tenant: {{ azure.tenant }}
  accessPolicy:
    inbound:
      rules:
        - application: {{ name }}
        - application: {{ azure.bidraggcpproxy_app }}
          cluster: {{ azure.bidraggcpproxy_cluster }}
          namespace: bidrag
    outbound:
      external:
        - host: {{ azure.familiebasak_url }}
        - host: {{ azure.bidraggcpproxy_url }}
        - host: {{ azure.kontantstotte_url }}
  image: {{ image }}
  liveness:
    path: /actuator/health
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /actuator/health
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /actuator/prometheus
  resources:
    limits:
      cpu: 1000m
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 1024Mi
  replicas:
    cpuThresholdPercentage: 80
    max: 4
    min: 2
  ingresses:
    - {{ ingress }}
  env:
    - name: FAMILIEBASAK_URL
      value: https://{{ azure.familiebasak_url }}
    - name: FAMILIEBASAK_SCOPE
      value: {{ azure.familiebasak_scope }}
    - name: BIDRAGGCPPROXY_URL
      value: https://{{ azure.bidraggcpproxy_url }}
    - name: BIDRAGGCPPROXY_SCOPE
      value: {{ azure.bidraggcpproxy_scope }}
    - name: KONTANTSTOTTE_URL
      value: https://{{ azure.kontantstotte_url }}
    - name: KONTANTSTOTTE_SCOPE
      value: { { azure.kontantstotte_scope } }
  gcp:
    sqlInstances:
      - name: {{ dbname }}
        type: POSTGRES_12
        databases:
          - name: {{ dbname }}
            envVarPrefix: DB
