apiVersion: "nais.io/v1alpha1"
kind: Application
metadata:
  name: bidrag-grunnlag
  namespace: bidrag
  labels:
    team: bidrag
spec:
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: bidrag-grunnlag
  image: {{ image }}
  liveness:
    path: /bidrag-grunnlag/actuator/health
    initialDelay: 70
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /bidrag-grunnlag/actuator/health
    initialDelay: 70
    timeout: 1
  prometheus:
    enabled: true
    path: /bidrag-grunnlag/actuator/prometheus
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  ingresses:
    - https://bidrag-grunnlag.intern.nav.no
  gcp:
    sqlInstances:
      - name: bidrag-grunnlag
        type: POSTGRES_12
        cascadingDelete: true
        databases:
          - name: bidrag-grunnlag-db
            envVarPrefix: DB