apiVersion: "nais.io/v1alpha1"
kind: Application
metadata:
  name: bidrag-grunnlag
  namespace: bidrag
  labels:
    team: bidrag
spec:
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: bidrag-grunnlag
        - application: bidrag-gcp-proxy
          cluster: prod-fss
          namespace: bidrag
    outbound:
      external:
        - host: familie-ba-sak.prod-fss-pub.nais.io
        - host: bidrag-gcp-proxy.prod-fss-pub.nais.io/bidrag-gcp-proxy
  image: {{ image }}
  liveness:
    path: /bidrag-grunnlag/actuator/health
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /bidrag-grunnlag/actuator/health
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /bidrag-grunnlag/actuator/prometheus
  resources:
    limits:
      cpu: 1000m
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 1024Mi
  ingresses:
    - https://bidrag-grunnlag.intern.nav.no
  gcp:
    sqlInstances:
      - name: bidrag-grunnlag-prod
        type: POSTGRES_12
        cascadingDelete: true
        databases:
          - name: bidrag-grunnlag-prod
            envVarPrefix: DB