-- Table: stonader

-- DROP TABLE stonader;

CREATE TABLE IF NOT EXISTS stonader
(
    stonad_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    grunnlagspakke_id integer NOT NULL,
    person_id integer NOT NULL,
    type varchar(255) NOT NULL,
    periode_fra char(6) NOT NULL,
    periode_til char(6),
    belop float NOT NULL,
    manuelt_beregnet boolean DEFAULT false NOT NULL,
    CONSTRAINT stonader_pkey PRIMARY KEY (stonad_id),
    CONSTRAINT grunnlagspakke_fkey FOREIGN KEY (grunnlagspakke_id)
        REFERENCES grunnlagspakke (grunnlagspakke_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    UNIQUE (stonad_id, grunnlagspakke_id)
)

    TABLESPACE pg_default;