-- Table: inntekt

-- DROP TABLE inntekt;

CREATE TABLE IF NOT EXISTS inntekt
(
    inntekt_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    grunnlagspakke_id integer NOT NULL,
    person_id integer NOT NULL,
    type varchar(255) NOT NULL,
    gyldig_fra date NOT NULL,
    gyldig_til date NOT NULL,
    aktiv boolean DEFAULT true NOT NULL,
    hentet_tidspunkt timestamp DEFAULT now() NOT NULL,
    bruk_fra timestamp DEFAULT now() NOT NULL,
    bruk_til timestamp,
    CONSTRAINT inntekt_pkey PRIMARY KEY (inntekt_id),
    CONSTRAINT grunnlagspakke_fkey FOREIGN KEY (grunnlagspakke_id)
        REFERENCES grunnlagspakke (grunnlagspakke_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    UNIQUE (inntekt_id, grunnlagspakke_id)
)

    TABLESPACE pg_default;