-- Table: inntektspost_skatt

-- DROP TABLE inntektspost_skatt;

CREATE TABLE IF NOT EXISTS inntektspost_skatt
(
    inntektspost_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    inntekt_id integer NOT NULL,
    type varchar(255) NOT NULL,
    belop float NOT NULL,
    CONSTRAINT inntektspost_skatt_pkey PRIMARY KEY (inntektspost_id),
    CONSTRAINT inntekt_skatt_fkey FOREIGN KEY (inntekt_id)
        REFERENCES inntekt_skatt (inntekt_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    UNIQUE (inntekt_id, type)
)

    TABLESPACE pg_default;
