-- Table: post

-- DROP TABLE post;

CREATE TABLE IF NOT EXISTS post
(
    post_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    inntekt_id integer NOT NULL,
    periode_fra date NOT NULL,
    periode_til date,
    opptjent_fra date NOT NULL,
    opptjent_til date,
    belop float NOT NULL,
    CONSTRAINT post_pkey PRIMARY KEY (post_id),
    CONSTRAINT inntekt_fkey FOREIGN KEY (inntekt_id)
        REFERENCES inntekt (inntekt_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    UNIQUE (post_id, inntekt_id)
)

    TABLESPACE pg_default;