-- Table: grunnlag_pakke

-- DROP TABLE grunnlag_pakke;

CREATE TABLE IF NOT EXISTS grunnlag_pakke
(
    grunnlag_pakke_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    opprettet_av varchar(255) NOT NULL,
    opprettet_timestamp timestamp DEFAULT now() NOT NULL,
    CONSTRAINT grunnlag_pakke_pkey PRIMARY KEY (grunnlag_pakke_id)
)

    TABLESPACE pg_default;