-- Table: husstandsmedlemskap

-- DROP TABLE husstandsmedlemskap;

CREATE TABLE IF NOT EXISTS husstandsmedlemskap
(
    husstandsmedlemskap_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    grunnlagspakke_id integer NOT NULL,
    part_person_id varchar(50) NOT NULL,
    navn varchar(255),
    foedselsdato date,
    husstandsmedlem_person_id varchar(50),
    er_barn_av_bm_bp boolean,
    periode_fra date,
    periode_til date,
    aktiv boolean DEFAULT true NOT NULL,
    bruk_fra timestamp DEFAULT now() NOT NULL,
    bruk_til timestamp,
    hentet_tidspunkt timestamp DEFAULT now() NOT NULL,
    CONSTRAINT husstandsmedlemskap_pkey PRIMARY KEY (husstandsmedlemskap_id),
    UNIQUE (husstandsmedlemskap_id, grunnlagspakke_id)
)
    TABLESPACE pg_default;

CREATE INDEX idx_husstandsmedlemskap_1 ON husstandsmedlemskap(grunnlagspakke_id, aktiv);

