-- Table: inntekt

-- DROP TABLE inntekt;

CREATE TABLE IF NOT EXISTS inntekt
(
    inntekt_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    grunnlag_pakke_id integer NOT NULL,
    person_id integer NOT NULL,
    type_inntekt varchar(255) NOT NULL,
    CONSTRAINT inntekt_pkey PRIMARY KEY (inntekt_id),
    CONSTRAINT grunnlag_pakke_fkey FOREIGN KEY (grunnlag_pakke_id)
        REFERENCES grunnlag_pakke (grunnlag_pakke_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    UNIQUE (inntekt_id, grunnlag_pakke_id)
)

    TABLESPACE pg_default;