-- Table: inntektspost

-- DROP TABLE inntektspost;

CREATE TABLE IF NOT EXISTS inntektspost
(
    inntektspost_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    inntekt_id integer NOT NULL,
    utbetalingsperiode char(6) NOT NULL,
    opptjeningsperiode_fra date,
    opptjeningsperiode_til date,
    opplysningspliktig_id varchar(20),
    inntekt_type varchar(50) NOT NULL,
    fordel_type varchar(50) NOT NULL,
    beskrivelse varchar(50) NOT NULL,
    belop float NOT NULL,
    CONSTRAINT post_pkey PRIMARY KEY (inntektspost_id),
    CONSTRAINT inntekt_fkey FOREIGN KEY (inntekt_id)
        REFERENCES inntekt (inntekt_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    UNIQUE (inntekt_id, utbetalingsperiode, opplysningspliktig_id, inntekt_type, fordel, beskrivelse)
)

    TABLESPACE pg_default;