-- Table: stonad

-- DROP TABLE stonad;

CREATE TABLE IF NOT EXISTS stonad
(
    stonad_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    grunnlagspakke_id integer NOT NULL,
    person_id varchar(50) not null,
    type varchar(255) NOT NULL,
    periode_fra date NOT NULL,
    periode_til date,
    belop float NOT NULL,
    manuelt_beregnet boolean DEFAULT false NOT NULL,
    hentet_tidspunkt timestamp DEFAULT now() NOT NULL,
    CONSTRAINT stonader_pkey PRIMARY KEY (stonad_id),
    CONSTRAINT grunnlagspakke_fkey FOREIGN KEY (grunnlagspakke_id)
        REFERENCES grunnlagspakke (grunnlagspakke_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    UNIQUE (stonad_id, grunnlagspakke_id)
)

    TABLESPACE pg_default;